name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pylint
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: poetry install

    - name: Analysing the code with pylint
      run: |
        # C0114: Missing module docstring
        # C0115: Missing class docstring
        # C0116: Missing function or method docstring
        # R0903: Too few public methods (we know what we are doing)
        pylint -d C0114,C0115,C0116,R0903 $(git ls-files '*.py')

